### ISSUE TITLE
Skipping doesn't seem to work (logged in as admin)

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#70] opened 2020-07-20 22:45 UTC
Sometimes, If I press skip, nothing happens OR sometimes the song starts over (but doesn't play audio..)  Seemingly, once it happens, everything else seems to not work (see below) 

![image](https://user-images.githubusercontent.com/2148511/87993341-daf81380-caaf-11ea-9297-8a035ca5e8b0.png)

Looks like all the playback controls don't do anything once I get the 'skip issue'...   If I click pause, the progress bar just keeps marching across the screen... even with no audio.. 

Volume control appears to work. 

My files are located on a spinning HD at /mnt/raveberryhd/Music  (in case that may have something to do with it).. Installed on a Pi 3 B v1.2

**Comment by raveberry** [comment] 2020-07-21 10:11
This sounds like mopidy is unhappy. If it encounters an error it refuses additional commands and needs to be restarted. I had this issue during development once in a while, but in production it doesn't happen usually.
Does it persist through reboots? Does it occur a lot?

`journalctl -xe -u mopidy` should tell you the reason for the error. Please look into `/opt/raveberry/logs/{error,info}.log` as well if you find anything related.

**Comment by tiny-e** [comment] 2020-07-21 15:32
Not sure about this 1 second timeout...   The server has been running for about an hour with no audio output, as soon as I loaded the web interface, it began to play the song.   Eventually the song will end, but the server will sit there silently and not load the next song in the queue. 

Just now when I loaded into the webui, it shows that a different song (from "Everlong" is playing.. 

![image](https://user-images.githubusercontent.com/2148511/88074763-74213b80-cb3d-11ea-8f95-b687b4897ffc.png)


`-- Logs begin at Tue 2020-07-21 09:52:29 CDT, end at Tue 2020-07-21 10:27:33 CDT. --
Jul 21 09:52:39 raveberry systemd[1]: Starting Mopidy music server...
-- Subject: A start job for unit mopidy.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mopidy.service has begun execution.
--
-- The job identifier is 87.
Jul 21 09:52:39 raveberry systemd[1]: Started Mopidy music server.
-- Subject: A start job for unit mopidy.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit mopidy.service has finished successfully.
--
-- The job identifier is 87.
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.2
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.config Loading config from command line options
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.__main__ Enabled extensions: softwaremixer, m3u, stream, http, file
Jul 21 09:52:50 raveberry mopidy[499]: INFO     [MainThread] mopidy.__main__ Disabled extensions: spotify, soundcloud
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__ Found soundcloud configuration errors. The extension has been automatically disabled:
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__   soundcloud/auth_token must be set.
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__ Found spotify configuration errors. The extension has been automatically disabled:
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__   spotify/username must be set.
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__   spotify/password must be set.
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__   spotify/client_id must be set.
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__   spotify/client_secret must be set.
Jul 21 09:52:50 raveberry mopidy[499]: WARNING  [MainThread] mopidy.__main__ Please fix the extension configuration errors or disable the extensions to silence these messages.
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [HttpFrontend-8] mopidy.http.actor HTTP server running at [::ffff:127.0.0.1]:6680
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Jul 21 09:52:52 raveberry mopidy[499]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "rgvolume ! audioconvert ! audioresample ! pulsesink server=127.0.0.1"
Jul 21 10:27:33 raveberry mopidy[499]: WARNING  [FileBackend-3] mopidy.file.library Failed looking up file:///var/www/Music/raveberry/local_library/Foo Fighters/Greatest Hits/16 Everlong (acoustic).mp3: Timeout after 1000ms`

**Comment by tiny-e** [comment] 2020-07-21 17:58
Getting back to this (over my lunch) looks like Mopidy is still stuck on that file... it keeps trying to replay it.  Survives resets and full reboots.

**Comment by raveberry** [comment] 2020-07-21 21:13
The first thing you noted is to be expected. The server only starts up when the first request is made, so that is not problematic.

The timeout thing is weird though. The problem probably persists because mopidy continuously tries to play that file and each restart of Raveberry tries to replay the same song.
There are multiple things you can try:
* Log into `/admin` and delete all entries in "Current songs" and "Queued songs", then restart the server with `systemctl restart daphne`. This will clear the queue, allowing you to try different songs. Now you could find out if the same behavior occurs for other songs as well.
* Copy some songs to the sd-card of the raspberry pi and change the local library to the new location. Maybe the timeout is not enough for mopidy to fetch the file from the external medium.
* Maybe the problem is solved by increasing the timout. Add a new section `[file]` to `/etc/mopidy/mopidy.conf` with the new config `metadata_timeout = 3000` (Refer to [this page](https://docs.mopidy.com/en/latest/ext/file/)). Afterwards a `systemctl restart mopidy` is required.

Hope this helps you solve the problem.

**Comment by tiny-e** [comment] 2020-07-21 22:07
> The first thing you noted is to be expected. The server only starts up when the first request is made, so that is not problematic.
> 
> The timeout thing is weird though. The problem probably persists because mopidy continuously tries to play that file and each restart of Raveberry tries to replay the same song.
> There are multiple things you can try:
> 
> * Log into `/admin` and delete all entries in "Current songs" and "Queued songs", then restart the server with `systemctl restart daphne`. This will clear the queue, allowing you to try different songs. Now you could find out if the same behavior occurs for other songs as well.
> * Copy some songs to the sd-card of the raspberry pi and change the local library to the new location. Maybe the timeout is not enough for mopidy to fetch the file from the external medium.
> * Maybe the problem is solved by increasing the timout. Add a new section `[file]` to `/etc/mopidy/mopidy.conf` with the new config `metadata_timeout = 3000` (Refer to [this page](https://docs.mopidy.com/en/latest/ext/file/)). Afterwards a `systemctl restart mopidy` is required.
> 
> Hope this helps you solve the problem.

I think the timeout is causing the issue.  As a test (previous to your reply) I disabled the hard drive's sleep ability with hdparm...  to see if that fixes anything.  

When I look at my local library section in /settings, It shows no songs... if I can the library it shows x found / x scanned /0 added..  Assume that's not normal.   Searching for artists/titles does work though.. 
![2020-07-21 13_08_51-Window](https://user-images.githubusercontent.com/2148511/88111987-92565e00-cb74-11ea-9731-52a6e0749321.png)

![2020-07-21 14_02_26-Window](https://user-images.githubusercontent.com/2148511/88112001-9b472f80-cb74-11ea-9c29-da08fa4fffd2.png)

**Comment by raveberry** [comment] 2020-07-22 09:19
Apparently increasing the timeout did not fix it?

In `/settings` you add a folder to the library of Raveberry. If you already scanned the folder, any additional scan will not add the same songs a second time. That's why it says "0 added".

The page you delete the queue at is `/admin`. It's the admin panel of django (the webserver), not Raveberry. There you can directly manipulate database entries. The credentials are the same as for Raveberry.

![admin](https://user-images.githubusercontent.com/53476237/88159061-15c38e00-cc0d-11ea-8b03-0b779111d852.png)

**Comment by tiny-e** [comment] 2020-07-22 16:35
Thanks for the information--  

As of now, I think the timeout/hdparm thing has helped.  I've ordered a USB stick that should hopefully serve to alleviate the timing based issues (vs rotating drive).  

Sorry for so many questions... I've been reading along here, checking out the docs -- but unless I'm missing something, a lot of these things aren't written down (?).

Is there a working wiki / forum / discord, etc. for general questions I should be using?

**Comment by tiny-e** [comment] 2020-07-22 17:29
Just now I had it fail with the same timeout error, only at 3000 ms this time..

**Comment by raveberry** [comment] 2020-07-23 08:24
Well if the problem actually is the long delay of your hard drive then the only thing you can do is probably increasing the timeout even further.

You are right that there is not much documentation yet. I keep on postponing it because
* I did not know if anybody actually ends up using this project. This seems to be invalid now, which make me very happy ;)
* There is a lot of stuff that could be written about, and I'm not sure which aspects require the most information. Issues like this help indicate these spots.
* Raveberry is still changing. Sometimes having outdated documentation is more confusing than having no documentation.
* This is my side project and writing documentation takes time and is not a lot of fun.

That said, raising issues is currently the best way to have your problems solved. I will try to help you as best as I can, and afterwards other people encountering the same issue can refer to the solution.

Proper documentation is of course the long term goal, it's just not there yet.

There is [a subreddit](https://www.reddit.com/r/Raveberry/), but not very much is going on there. Also, I usually respond to Github issues faster.

**Comment by tiny-e** [comment] 2020-07-23 15:16
This area works fine for me -- just didn't want to innundate the github issues with questions that may not be issues :) 

This is a cool project, and I appreciate the level of involvement/support.   My plan is to deploy this as a voting jukebox for boat/sandbar recreation, possibly with a low-power FM transmitter (legal) to allow other boats to tune in to music and play what they want / vote if something sucks.

**Comment by raveberry** [comment] 2020-07-23 17:50
It's all good, don't hesitate to open issues. They can be for suggestions, questions and discussion and don't need to revolve around a problem with the software. Bigger projects don't like discussion in github issues, but I don't mind.

Your plan sounds really cool! I'm curious about the results :)

**Comment by raveberry** [comment] 2020-07-26 20:40
Since increasing Mopidy's timeout apparently helped with this problem, I am going to close the issue.

**Comment by tiny-e** [comment] 2020-07-30 23:29
OK -- Fresh install with a new USB keychain drive ... 
`Jul 30 15:29:00 raveberry mopidy[5408]: WARNING  [FileBackend-3] mopidy.file.library Failed looking up file:///media/pi/raveberryhd/Music/local_library/Tom Petty and the Heartbreakers/Anthology_ Through the Years/1-15 You Got Lucky.mp3: Timeout after 3000ms
Jul 30 17:07:41 raveberry mopidy[5408]: WARNING  [FileBackend-3] mopidy.file.library Failed looking up file:///media/pi/raveberryhd/Music/local_library/Tom Petty and the Heartbreakers/Anthology_ Through the Years/2-22 Jammin_ Me.mp3: Timeout after 3000ms`

New USB is mounted at /mnt --although raspberry OS (and other flavors of Linux, I think, likes to mount external media at /media.

Upped the timeout to 5000ms.. still throws an error...  --Note that I can play this file just fine with Plex/anything else.   Maybe I'll chmod the whole drive to wide open to see what happens...

**Comment by raveberry** [comment] 2020-08-04 19:54
Sorry, I missed this. Going to reopen the issue if it still persists.

The path to the local library of Raveberry is stored in a symlink in its cache directory (by default in `/var/www/Music/raveberry/local_library`). If the structure of your library is identical and only the mounting point changed, you can simply change the symlink to point to the new location. Your scanned songs can stay in the database and should work again after the change.

Are you still using the HDD? The read latencies are the only explanation I have for the timout errors, as I've never encountered them before.

**Comment by tiny-e** [comment] 2020-08-04 22:19
I'm using a USB 3 flash drive now... so should be no issues with latency there.   I just had a song hang and can't skip it..  Was tailing the log for mopidy, maybe this helps?: 
`Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.core.playback Changing state: playing -> stopped
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.core.playback Triggering playback state change event
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.listener Sending playback_state_changed to CoreListener: {'old_state': 'playing', 'new_state': 'stopped'}
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.core.playback Triggering track playback ended event
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.core.tracklist Triggering event: tracklist_changed()
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.listener Sending tracklist_changed to CoreListener: {}
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [Core-6] mopidy.listener Sending track_playback_ended to CoreListener: {'tl_track': TlTrack(tlid=21, track=Track(album=Album(artists=[Artist(musicbrainz_id='f93dbc64-6f08-4033-bcc7-8a0bb4689849', name='Tom Petty and the Heartbreakers')], date='2000', musicbrainz_id='117d3874-d5de-439c-8d57-6a6ad1ab8ca4', name='Anthology: Through the Years', num_discs=2, num_tracks=34), artists=[Artist(musicbrainz_id='f93dbc64-6f08-4033-bcc7-8a0bb4689849', name='Tom Petty and the Heartbreakers')], comment='tagged by headphones/beets', composers=[Artist(name='Tom Petty')], date='2000', disc_no=1, genre='Rock', length=162847, musicbrainz_id='c94ebb20-1a71-4d72-942d-3b32cf18c260', name='Breakdown', track_no=1, uri='file:///mnt/USBMusic/Music/local_library/Tom Petty and the Heartbreakers/Anthology - Through the Years/1-01 Breakdown.mp3')), 'time_position': 162873}
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [HttpServer] mopidy.http.handlers Received RPC message from 127.0.0.1: b'{"jsonrpc": "2.0", "id": 0, "method": "core.playback.get_state"}'
Aug 04 17:14:53 raveberry mopidy[8770]: INFO     [HttpServer] tornado.access 200 POST /mopidy/rpc (127.0.0.1) 4.85ms
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [HttpServer] mopidy.http.handlers Received RPC message from 127.0.0.1: b'{"jsonrpc": "2.0", "id": 0, "method": "core.playback.get_state"}'
Aug 04 17:14:53 raveberry mopidy[8770]: INFO     [HttpServer] tornado.access 200 POST /mopidy/rpc (127.0.0.1) 4.68ms
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [HttpServer] mopidy.http.handlers Received RPC message from 127.0.0.1: b'{"jsonrpc": "2.0", "id": 0, "method": "core.playback.get_time_position"}'
Aug 04 17:14:53 raveberry mopidy[8770]: INFO     [HttpServer] tornado.access 200 POST /mopidy/rpc (127.0.0.1) 5.15ms
Aug 04 17:14:53 raveberry mopidy[8770]: DEBUG    [HttpServer] mopidy.http.handlers Received RPC message from 127.0.0.1: b'{"jsonrpc": "2.0", "id": 0, "method": "core.playback.get_current_track"}'
Aug 04 17:14:53 raveberry mopidy[8770]: INFO     [HttpServer] tornado.access 200 POST /mopidy/rpc (127.0.0.1) 3.67ms

`

**Comment by raveberry** [comment] 2020-08-05 07:07
What exactly did you do during this log?
Did you press skip, the song stopped playing (at 17:14:53), but in the interface the current song did not change?

**Comment by tiny-e** [comment] 2020-08-05 14:17
So.. I think there is an issue with that particular file (which plays fine on anything else... ) I think the song is only like 3 minutes long.. 

Noticed that it was sitting there doing nothing, tried to skip.   The progress bar, generally, keeps moving --even if nothing is happening. 

I can queue up some songs again, put that one in the middle and see what happens, then report back.

**Comment by tiny-e** [comment] 2020-08-05 19:44
Naturally, the suspected file played fine this time around.. 
Right now, this song is playing, and the UI is no longer responding... 
'ug 05 14:11:50 raveberry mopidy[18646]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Resource not found.
Aug 05 14:11:50 raveberry mopidy[18646]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Aug 05 14:11:50 raveberry mopidy[18646]: WARNING  [Core-6] mopidy.core.tracklist Track is not playable: file:///mnt/USBMusic/Music/local_library/Pink Floyd/The Wall/3-10 Don't Leave Me Now (Demo #1).mp3
Aug 05 14:11:52 raveberry mopidy[18646]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Resource not found.
Aug 05 14:11:52 raveberry mopidy[18646]: WARNING  [Audio-2] mopidy.audio.actor Setting GStreamer state to GST_STATE_PLAYING failed
Aug 05 14:11:52 raveberry mopidy[18646]: WARNING  [Core-6] mopidy.core.tracklist Track is not playable: file:///mnt/USBMusic/Music/local_library/Pink Floyd/The Wall/3-10 Don't Leave Me Now (Demo #1).mp3
Aug 05 14:40:28 raveberry mopidy[18646]: WARNING  [FileBackend-3] mopidy.file.library Failed looking up file:///mnt/USBMusic/Music/local_library/Prince/Originals/12 Love... Thy Will Be Done.mp3: Timeout after 9000ms'

**Comment by raveberry** [comment] 2020-08-07 20:08
Maybe this is a problem with the external medium again. I know it's unlikely since you already tried two different devices, but it still is a possibility. Could you try to copy your library (or a part of it) onto the Raspberry Pi's sd-card and play the music from there?
This should eliminate all timing issues with external media.

**Comment by tiny-e** [comment] 2020-08-07 20:15
I can try.  

Things tend to have less issues with the USB stick than the HDD.  Right now (for ease of work) the pi is running a desktop environment.  Do you think that could be slowing things down enough to cause issues?   Looking at it (via conky.. which I'm sure uses some resources too) shows pretty low CPU utilization virtually all of the time.

**Comment by raveberry** [comment] 2020-08-09 14:14
I can't imagine that the desktop environment has any negative impact on the music being loaded. Especially if it is idling, it should not consume any significant amount of resources.

**Comment by raveberry** [comment] 2020-09-21 10:19
Closing due to inactivity.
Feel free to reopen if the issue persists.

**Closed by raveberry** 2020-09-21 10:19 UTC
Labels: bug
