### ISSUE TITLE
Docker Set-up on NAS

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#32] opened 2020-05-04 18:11 UTC
Original post from REDDIT:

First, congrats on a fantastic app, love this idea, and with all the madness happening right now, I can see this being used a lot for online gatherings. I wonder if you could help me. I am trying to get this running on my NAS using docker-compose. I managed to get Raveberry running and it seems to work fine. I also installed Icecast and I can get to the web interface. When I try to enable streaming in Raveberry it doesn't find Icecast. The 2 are in the same docker-compose.yml file and therefore run in the same network but I think I need to install Icecast as part of the Raveberry install, not separately, however, I'm not sure how to go about this. Any pointers would be much appreciated :)

Response from RAVEBERRY :)

Thank you!

If you want to make streaming work with the docker setup, you probably need to change mopidy's config. The configuration the container uses by default can be found in docker/mopidy.conf. Change the output variable to something like this:

output = lamemp3enc ! shout2send async=false mount=stream ip=<icecast-container> port=8000 password=<password>

Then map the config into the mopidy container as described in the compose file. If mopidy is then able to stream to icecast, you probably have to access the stream at <icecast-container>:8000/stream, as the nginx container does not yet redirect this url.

If you get it working, please let me know so others can profit from your effort as well!

Also, feel free to move the discussion to Github if you have further questions.

Edit: here is a link to mopidy's documentation about icecast

**Comment by MickyGX** [comment] 2020-05-04 18:14
So I tried what you suggested and whenever I added the volume into my compose file, it built ok but going to Raveberry now gave me:

500 Internal Server Error
Exception inside application.

Daphne

I created both a blank file and one with the output line above in it and called it mopidy.conf. I changed the permissions to make sure the docker user could access the files but nothing worked. Do I need to have something in the file already?

**Comment by MickyGX** [comment] 2020-05-04 18:36
So I managed to get the config to work I think, atleast I can see your website with the conf volume mounted. I had to add ports: - 6680:6680 to mopidy docker-compose and this started working again, however, when I try and Enable Streaming it tells me to install icecast2. Is there a way I can tell if it is loading the conf file ok?

**Comment by MickyGX** [comment] 2020-05-04 22:00
So I've been playing with this now for most of the day and I can't get Raveberry to recognize Icecast no matter what I do. Not sure if its relevant but because I am running this on a NAS and not a Pi port 80 is already taken for Nginx so I have set the outward facing port to 89 i.e. ports: -89:80. It seems to work fine and Raveberry is displayed correctly. Also I can see Icecast and Mopidy screens on their relevant ports. Mopidy is loading the config correctly:

`[audio]
output = lamemp3enc ! shout2send async=false mount=stream ip=192.168.0.2 port=8000 password=password

[http]
hostname = 0.0.0.0 #Note only works with 0.0.0.0, tried localhost, 127.0.0.1 and 192.168.0.2

[spotify]
username =
password =
client_id =
client_secret =
search_album_count = 1
search_artist_count = 1
search_track_count = 1
# do not refresh the user's playlists as they are not needed and only delay mopidy's restart
allow_playlists = false
private_session = true`

And this is my docker-compose file:

`version: "3.4"
volumes:
    static-files:
    songs-cache:
        # If you want to access downloaded files on your host system,
        # uncomment the following lines and choose a folder.
        driver_opts:
            type: none
            o: bind
            device: /path/to/music/
    db:
        container_name: postgres
        image: postgres
        #network_mode: host
        environment:
            - POSTGRES_DB=raveberry
            - POSTGRES_USER=raveberry
            - POSTGRES_PASSWORD=raveberry
        restart: always
    redis:
        container_name: redis
        image: redis
        #network_mode: host
        restart: always
    mopidy:
        container_name: mopidy
        image: raveberry/raveberry-mopidy
        #network_mode: host
        # environment:
            # - PUID=${PUID}
            # - PGID=${PGID}
            # - TZ=${TZ}
            # - UMASK=002
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - songs-cache:/Music/raveberry
      # Comment this line if pulse does not work.
            - /run/user/${UID:-1001}/pulse:/run/user/105/pulse
      # If you want to use spotify, 
      # uncomment this line with a path to a config file containing the spotify credentials
            - /path/to/config/mopidy.conf:/config/mopidy.conf:rw
        ports:
            - 6680:6680
        restart: always
    # Use these three lines to use alsa if pulse is not working.
    #user: root
    #devices:
    #  - "/dev/snd:/dev/snd"
    daphne:
        container_name: raveberry
        image: raveberry/raveberry
        #network_mode: host
        environment:
            - ADMIN_PASSWORD=password
            - MOD_PASSWORD=password
            - PAD_PASSWORD=password
            - DOCKER=1
        command: bash -c "DJANGO_MOCK=1 python manage.py compilescss && DJANGO_MOCK=1 python manage.py migrate --noinput && scripts/create_users.sh && /usr/local/bin/daphne --bind 0.0.0.0 --port 9000 main.asgi:application"
        ports:
            - 9000:9000
        # expose:
            # - 9000
        volumes:
            - static-files:/opt/raveberry/static
            - songs-cache:/Music/raveberry
        depends_on:
            - db
            - redis
            - mopidy
        restart: always

    nginx:
        container_name: raveberry-nginx
        image: raveberry/raveberry-nginx
        ports:
            - 89:80
        volumes:
            - static-files:/usr/share/nginx/static
        depends_on:
            - daphne
        restart: always

    icecast:
        container_name: icecast
        image: infiniteproject/icecast
        volumes:
            #- ${DOCKDIR}/raveberry/icecast2/logs:/var/log/icecast2:rw
            #- ${DOCKDIR}/icecast2/icecast.xml:/etc/icecast2/icecast.xml
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK=002
            - ICECAST_SOURCE_PASSWORD=password
            - ICECAST_ADMIN_PASSWORD=password
            - ICECAST_PASSWORD=password
            - ICECAST_RELAY_PASSWORD=password
            - ICECAST_ADMIN_USERNAME=admin
            - ICECAST_ADMIN_EMAIL=admin@domain.com
            - ICECAST_HOSTNAME=0.0.0.0
            - ICECAST_LOCATION=America
        ports:
            - 8000:8000
        restart: always`

Excuse the mess haven't tidied it up yet. If anything obvious I'm doing wrong would appreciate the help. Determined to get this working one way or the other. Thanks

**Comment by MickyGX** [comment] 2020-05-04 22:10
[new 1.txt](https://github.com/raveberry/raveberry/files/4577964/new.1.txt)
Attached as file for clearer reading

**Comment by raveberry** [comment] 2020-05-05 07:10
Hm. The first 500 probably came from the webserver not being able to connect to mopidy. It tries to connect to the `mopidy` host at port 6680. I thought that it should work inside the docker-compose network without explicit port mapping. Great that you managed to fix this!

You can check the config mopidy loaded by taking a look at its logs. It will tell you to which value it set `output`.

Raveberry will tell you to "Please install icecast2", because it checks if the `icecast2` service is installed on its system. This is not the case in the docker setup of course, so you get this message. However, if mopidy uses the correct configuration, this should not be a problem, streaming should work anyway.

Are you sure that `192.168.0.2` is the ip of your icecast container? According to [gstreamer's docu](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-good/html/gst-plugins-good-plugins-shout2send.html#GstShout2send--ip) you should also be able to specify a hostname, which should be `icecast` (the name of the docker container) in your case.

**Comment by MickyGX** [comment] 2020-05-05 13:14
Thank you for the reply, appreciate you taking the time to help me.

So thats the actual ip's of the containers I have setup, the left column shows the container name. I have tried the actual container IP's, the hostnames, the host computer IP's and nothing seems to work:

![image](https://user-images.githubusercontent.com/1932078/81066995-9e028480-8ea3-11ea-9234-2a66ab10c452.png)

This is my mopidy config file:

![image](https://user-images.githubusercontent.com/1932078/81069935-3438a980-8ea8-11ea-94ea-eb05b197b6ca.png)

I'm starting to think I need to run all the services in a single instance with combined dockerfile, but wouldn't know where to start with that.

Any suggestions?

**Comment by MickyGX** [comment] 2020-05-05 13:44
Just for info it appears that mopidy is connecting to icecast because everytime i restart mopidy the file_connections on the icecast admin page goes up by one:

![image](https://user-images.githubusercontent.com/1932078/81072961-8da2d780-8eac-11ea-90cf-221efc745edf.png)

**Comment by MickyGX** [comment] 2020-05-05 14:05
so an update, I thought I would just try to play some music in raveberry and check to see if icecast did anything. Lo and behold it showed a stream. Went to 192.168.0.2:8000/stream and i can hear the music! It still won't connect on Raveberry but it works for waht I want. Juts need to put both into a single webpage and share! Love this thanks. Please let me know if you want me to try anything out going forward. I don't mind being a guinea pig :)

**Comment by raveberry** [comment] 2020-05-05 15:01
Very nice!
So it was actually working but the stream did not show up without you playing any music?

If I get around to it I will probably integrate this into the documentation and provide a second `docker-compose.yml` for streaming. After all it was not too much configuration if one knows where to tweak.

**Comment by MickyGX** [comment] 2020-05-05 15:10
I guess it was but it is still saying install Icecast in Raveberry. Let me know if you do get round to it would be happy to try it out and test it. Ideal scenario would be to have all services in a single instance for docker so everything just works together, but obviously this doesn't matter for Pi.
Just another question, what directories would I have to map for raveberry so it doesn't lose my settings/data on container/server reboot?

**Comment by raveberry** [comment] 2020-05-06 06:42
When running in Docker Raveberry v0.5.6 now checks the presence of icecast differently and gives a more useful message.
Also I uploaded a second docker-compose.yml for a streaming setup that should work out of the box without any additional tweaking as I integrated the fixes from this issue.
I'd be happy to hear about how it works for you.

**Comment by MickyGX** [comment] 2020-05-07 12:08
I've set it up and a couple of issues:
1) No matter whats in the playlist the stream constantly plays silence.mp3
![image](https://user-images.githubusercontent.com/1932078/81292513-5873c200-9031-11ea-99d2-f99c9d7ad321.png)

2) Can't access stream no matter what I put in as password. I assumed user would be stream but tried a number of different combinations with password etc/ Now my raveberry/stream link works though just can't access it

**Comment by MickyGX** [comment] 2020-05-07 12:31
Few more things
1) When I click enable stream it still !Install Icecast
2) Tried pointing it to my icecast.xml file and it seems to ignore whats inside it like hostname, passwords etc. Assuming location in container as changed?
3) Is it possible to disable stream password altogether? Reason is I will be including this on my website which is already user and password restricted

**Comment by raveberry** [comment] 2020-05-07 12:53
1. Did update your containers? Sounds like you might be running old versions. Try running `docker-compose -f icecast.docker-compose.yml pull`.
2. The default credentials are raveberry:raveberry (maybe a little to hidden in streaming.md)
3. see 1.
4. I did a copy paste error when adding the config hint into the compose file. Now it contains the correct path in the container (`/etc/icecast.xml`). Good catch!
5. Yes. Now that you can add a config to the correct path, just pass one that does not have the `<authentication>` tag in the `<mount>` tag for `<stream>`. Use the default config in `docker/icecast.xml` as reference.

**Comment by MickyGX** [comment] 2020-05-07 14:08
Its working now
1) I deleted all 6 containers but forgot to delete the images doh!
2)Left as default and can login
3)Now it says - 'Choose the correct docker-compose file to control streaming'
![image](https://user-images.githubusercontent.com/1932078/81303183-fcb13500-9040-11ea-9e99-30d44d80ee06.png)
As I said streaming is working and shows status as true but can't enable/disable it. Not an issue for me but for reference
4) If i add:
![image](https://user-images.githubusercontent.com/1932078/81303497-603b6280-9041-11ea-81b1-b8daebe10e24.png)
to my docker-compose file I get:
![image](https://user-images.githubusercontent.com/1932078/81303641-94af1e80-9041-11ea-8082-05b4c8f3aaaa.png)
I can live without this for now but would really like to turn off stream password.
5) See 4

Excellent work by the way. Absolutely love this. I have an online poker game every Friday which runs off my server and we video chat via zoom. Music choice is always an issue and you find people listening to their own music, start singing (badly) and end up muting them lol. This way atleast we can all have a say in what we listen to. Unfortunately it won't stop the bad singing lol.

Really appreciate you helping me getting this working outside of Raspberry Pi. And anything I can to further help let me know!

**Comment by raveberry** [comment] 2020-05-07 17:29
The "Choose the correct file" error is intended behavior, as it is currently not possible to change the streaming status in the docker setup and I do not plan to change that. Streaming can be enabled/disable by running the respective `docker-compose.yml`, which is what I tried to convey with this short message. Probably I should just indicate that by greying these options or hiding them completely.

You most likely get the icecast error because you used a config from your system, which does not have the `changeowner` directive enabled. If you use [this one](https://github.com/raveberry/raveberry/blob/master/docker/icecast.xml) you should be fine. There you can also delete the authentication part in the mountpoint to disable stream authentication.

Thank you for your feedback! It's nice to know that my project is actually useful and in operation somewhere else. If you just keep pointing out stuff that doesn't work quite right and make suggestions that is already worth a lot. I hope your next session works well!

I will now close this issue as the docker-setup appears to be working. Feel free to open new ones if more problems arise.

**Closed by raveberry** 2020-05-07 17:29 UTC
Labels: docker, streaming
