### ISSUE TITLE
Response slow, disconnected always showing

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#101] opened 2021-03-19 20:29 UTC
Ive tried 2 fresh installs and continue to see "Disconnected, trying to reconnect" on all pages when using the system. 
It works, just the response time is painfully slow.
Reviewed all logs, cannot find anything that would be related.

Can log in, but when first using the music interface there is a distinct 10 second delay.

**Comment by raveberry** [comment] 2021-03-19 21:40
Have you used older versions of Raveberry in the past?
There was a big frontend rework recently (0.7.9), and possibly this is the cause. Although it should have made things faster if anything. Do you see any errors in the browser console?

What hardware are you using?

**Comment by FluidExtractor** [comment] 2021-03-21 01:01
I'm also getting "Disconnected, trying to reconnect", but only when logged in as admin. Logging in with the built-in mod user doesn't produce the message. 
When logged in as admin, I'm also experiencing longer load times when switching pages, eg. going from main page to admin settings or LED settings. Queuing songs doesn't seem to be affected.
Raveberry is installed on a Pi 4, older version were never installed.

After the disconnected message pops up, this shows up in the browser console:
```
bundle.js:2 WebSocket connection to 'ws://raveberry/state/' failed: WebSocket is closed before the connection is established.
e._disconnect @ bundle.js:2
_handleError @ bundle.js:2
e._handleTimeout @ bundle.js:2
(anonymous) @ bundle.js:2
setTimeout (async)
(anonymous) @ bundle.js:2
Promise.then (async)
e._connect @ bundle.js:2
e @ bundle.js:2
136 @ bundle.js:2
n @ bundle.js:2
(anonymous) @ bundle.js:2
(anonymous) @ bundle.js:2
```

**Comment by raveberry** [comment] 2021-03-21 13:56
That is weird behavior I have not experienced yet, and unfortunately I can't reproduce it.

I don't know why loading pages as admin specifically should be slow. The one thing that only happens as admin is checking whether an upgrade is available, but that happens asynchronously and should not impact performance. Nevertheless, the next version will cache that fact for a day, so the effect should be further reduced.

The websocket error occurs when the connection is not properly closed or opened. Usually this is fixed after some hard refreshes (ctrl+F5).

I found another problem while looking for the cause of your performance issue: I forgot to import a widget that allows resorting, causing an error when voting mode was disabled. This will be fixed in the next release, but maybe it has something to do with the problem? Is the disconnected bar always there or only if voting is disabled?

**Comment by mxpowe** [comment] 2021-03-21 16:31
I have voting enabled, this is a RPI3, and i used most of the other versions before. First time experiencing this.

**Comment by raveberry** [comment] 2021-03-22 12:55
I tested a fresh install on a Pi 3 and could reproduce the behavior. I released 0.7.12 that should fix it.

The problem was that for some reason checking the availability of a new version prevented the websocket connection from opening. I don't know why, because the request is asynchronous, but delaying it for some seconds after the page has loaded allows the websocket to open normally.

Please let me know if this fixes the performance issues.

**Comment by FluidExtractor** [comment] 2021-03-22 15:20
After updating, everything is working as expected. The red disconnected bar, and long load times are gone now.

**Comment by mxpowe** [comment] 2021-03-22 18:10
New update fixed it! Thank you sir

**Comment by raveberry** [comment] 2021-03-22 21:09
Great! Thank you both for your issue report and fast responses.

**Closed by raveberry** 2021-03-22 21:09 UTC
