### ISSUE TITLE
Stream Stopping After Every Song

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#33] opened 2020-05-05 18:22 UTC
So after getting this working on my NAS and managed to get it to stream to a web browser or VLC I have 2 isues which I think are related:

1) Currently after everysong the stream stops. To start again you have to refresh stream and press play. and it then picks up at the point the song is in within Raveberry

2) Playing on multiple browsers the music goes out of sync which is made worse if a client pauses and then resumes a song

I am guessing both are related to Icecast and a setting of some sort but I can't currently get on to their website to check it out as it seems to be down and struggling finding an answer elsewhere. Thanks again

**Comment by raveberry** [comment] 2020-05-05 18:44
Ah, right. The problem is that icecast doesn't have a fallback for the stream.
Take a look at `scripts/system/enable_streaming`. This is my script that sets up icecast in a system installation.
You need to provide a fallback to a silent sound file as documented [here](https://docs.mopidy.com/en/latest/icecast/#fallback-stream) and change the icecast.xml accordingly.
The next few days I will probably upload a container that already has that built in.

The other issue is unrelated, I think. Every client needs to buffer the sound and these buffers will change from client to client. So desynchronization will probably be unavoidable.

**Comment by MickyGX** [comment] 2020-05-05 20:50
I added a volume to the webroot with the silence.mp3 file and modified the icecast.xml file as suggested but it didn't work. Looked at your script and I can follow it but I wouldn't know where to start in terms of implementing it. I'm assuming though thats what happens when you press the enable streaming button in the admin screen and why nothing happens because icecast is in a separate container. Also why most of the other buttons don't do anything for me.

If I had the know how I'd put all the separate apps into one container sort of mimicking being on a Pi so it would work as orignally intended. In the meantime I'll wait for the update :)

**Comment by raveberry** [comment] 2020-05-06 06:49
It could have been some path issues. The structure of the icecast container is a little different from the raspbian install, as I found out while building the Dockerfile. Should be fixed in the new docker setup.

Most of the buttons don't do anything as they only work in a system setup. I should probably visualize that by greying them out or something.

Also, integrating all services into one container is not a good idea. It would maybe simplify the migration from system install to docker, but it kind of defeats the point of containerization. Having a structured compose file that defines the interactions between the single-service containers is a cleaner solution, even if it's a little more work.

**Comment by raveberry** [comment] 2020-05-07 17:33
This should be fixed with the new docker-compose file that includes icecast. Can you confirm that?

**Comment by MickyGX** [comment] 2020-05-07 17:46
Yes this now sorted and working great thanks

**Closed** 2020-05-07 17:53 UTC
Labels: docker, streaming
